// supabase/functions/generate-report/index.ts
// Deploy: npx supabase functions deploy generate-report --project-ref xxxxxx

import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'

const supabase = createClient(
  Deno.env.get('SUPABASE_URL')!,
  Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!
)

// Helper: convert array of objects ke string CSV
function toCSV(headers: string[], rows: Record<string, any>[]): string {
  const headerRow = headers.join(',')
  const dataRows  = rows.map(row =>
    headers.map(h => {
      const val = row[h] ?? ''
      // Kalau value mengandung koma atau newline, wrap dengan quotes
      return String(val).includes(',') ? `"${val}"` : val
    }).join(',')
  )
  return [headerRow, ...dataRows].join('\n')
}

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Methods': 'POST, OPTIONS',
  'Access-Control-Allow-Headers': 'authorization, content-type',
}

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders })
  }

  try {
    // Ambil user dari JWT
    const authHeader = req.headers.get('Authorization')!
    const { data: { user }, error: authError } = await supabase.auth.getUser(
      authHeader.replace('Bearer ', '')
    )
    if (authError || !user) {
      return new Response(JSON.stringify({ error: 'Unauthorized' }), { status: 401 })
    }

    // Ambil business_id + nama user
    const { data: profile } = await supabase
      .from('users')
      .select('business_id, name, businesses(business_name)')
      .eq('id', user.id)
      .single()

    const businessId   = profile?.business_id
    const businessName = profile?.businesses?.business_name ?? 'Business'

    if (!businessId) {
      return new Response(JSON.stringify({ error: 'Business not found' }), { status: 404 })
    }

    // Ambil semua data yang diperlukan secara paralel
    const [txnRes, recRes, payRes, forecastRes] = await Promise.all([
      supabase
        .from('transactions')
        .select('transaction_date, type, category, description, amount, status, payment_method')
        .eq('business_id', businessId)
        .order('transaction_date', { ascending: false })
        .limit(500),

      supabase
        .from('receivables')
        .select('client_name, amount, due_date, status')
        .eq('business_id', businessId)
        .order('due_date', { ascending: true }),

      supabase
        .from('payables')
        .select('vendor_name, amount, due_date, status')
        .eq('business_id', businessId)
        .order('due_date', { ascending: true }),

      supabase
        .from('cashflow_forecasts')
        .select('start_date, end_date, total_projected_income, total_projected_expense, net_cashflow, forecast_details(forecast_date, predicted_income, predicted_expense, predicted_balance)')
        .eq('business_id', businessId)
        .order('generated_at', { ascending: false })
        .limit(1)
        .single(),
    ])

    const transactions = txnRes.data  ?? []
    const receivables  = recRes.data  ?? []
    const payables     = payRes.data  ?? []
    const forecast     = forecastRes.data

    // Generate tanggal untuk nama file
    const now       = new Date()
    const dateStr   = now.toISOString().split('T')[0]
    const timeStr   = now.toTimeString().split(' ')[0].replace(/:/g, '-')
    const timestamp = `${dateStr}_${timeStr}`

    // ── SECTION 1: Summary ──────────────────────────────────────────
    const totalIncome  = transactions.filter(t => t.type === 'INCOME').reduce((s, t) => s + Number(t.amount), 0)
    const totalExpense = transactions.filter(t => t.type === 'EXPENSE').reduce((s, t) => s + Number(t.amount), 0)
    const totalAR      = receivables.filter(r => r.status !== 'PAID').reduce((s, r) => s + Number(r.amount), 0)
    const totalAP      = payables.filter(p => p.status !== 'PAID').reduce((s, p) => s + Number(p.amount), 0)

    const summaryCSV = toCSV(
      ['metric', 'value'],
      [
        { metric: 'Business Name',         value: businessName },
        { metric: 'Report Generated At',   value: now.toISOString() },
        { metric: 'Generated By',          value: profile?.name ?? user.email },
        { metric: '',                      value: '' },
        { metric: 'Total Income (all time)',  value: totalIncome },
        { metric: 'Total Expense (all time)', value: totalExpense },
        { metric: 'Net Balance',              value: totalIncome - totalExpense },
        { metric: '',                         value: '' },
        { metric: 'Outstanding Receivables',  value: totalAR },
        { metric: 'Outstanding Payables',     value: totalAP },
        { metric: '',                         value: '' },
        { metric: 'Projected Income (90d)',   value: forecast?.total_projected_income  ?? 'N/A' },
        { metric: 'Projected Expense (90d)',  value: forecast?.total_projected_expense ?? 'N/A' },
        { metric: 'Net Cashflow (90d)',       value: forecast?.net_cashflow            ?? 'N/A' },
      ]
    )

    // ── SECTION 2: Transactions ─────────────────────────────────────
    const txnCSV = toCSV(
      ['transaction_date', 'type', 'category', 'description', 'amount', 'status', 'payment_method'],
      transactions
    )

    // ── SECTION 3: Receivables ──────────────────────────────────────
    const recCSV = toCSV(
      ['client_name', 'amount', 'due_date', 'status'],
      receivables
    )

    // ── SECTION 4: Payables ─────────────────────────────────────────
    const payCSV = toCSV(
      ['vendor_name', 'amount', 'due_date', 'status'],
      payables
    )

    // ── SECTION 5: Forecast details ─────────────────────────────────
    const forecastDetails = forecast?.forecast_details ?? []
    const forecastCSV = toCSV(
      ['forecast_date', 'predicted_income', 'predicted_expense', 'predicted_balance'],
      forecastDetails.sort((a: any, b: any) => a.forecast_date.localeCompare(b.forecast_date))
    )

    // Gabung semua section jadi satu file CSV dengan separator
    const fullCSV = [
      '=== FLOWGUARD FINANCIAL REPORT ===',
      '',
      '--- SUMMARY ---',
      summaryCSV,
      '',
      '--- TRANSACTIONS ---',
      txnCSV,
      '',
      '--- RECEIVABLES ---',
      recCSV,
      '',
      '--- PAYABLES ---',
      payCSV,
      '',
      '--- CASHFLOW FORECAST (90 DAYS) ---',
      forecastCSV,
    ].join('\n')

    // Upload ke Supabase Storage
    const filePath = `${businessId}/report_${timestamp}.csv`
    const { error: uploadError } = await supabase.storage
      .from('reports')
      .upload(filePath, fullCSV, {
        contentType: 'text/csv',
        upsert: false,
      })

    if (uploadError) throw new Error(`Upload gagal: ${uploadError.message}`)

    // Insert metadata ke tabel reports
    const { data: reportRow, error: insertError } = await supabase
      .from('reports')
      .insert({
        business_id:    businessId,
        generated_by:   user.id,
        report_type:    'cashflow_report',
        generated_date: dateStr,
        file_url:       filePath,
      })
      .select()
      .single()

    if (insertError) throw new Error(`Insert metadata gagal: ${insertError.message}`)

    return new Response(
      JSON.stringify({
        success:  true,
        report:   reportRow,
        filePath,
        stats: {
          transactionCount: transactions.length,
          receivableCount:  receivables.length,
          payableCount:     payables.length,
          hasForecast:      !!forecast,
        }
      }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    )

  } catch (err: any) {
    console.error('generate-report error:', err)
    return new Response(
      JSON.stringify({ error: err.message }),
      { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    )
  }
})
